wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1678870813.076938
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.10.6
      5: 0.13.11
      8:
      - 5
x:
  desc: null
  value: 0.014663103843449163
y:
  desc: null
  value: 7
